config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :description, presence: true, length: { minimum: 5, maximum: 1000 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    return if logged_in?

    flash[:danger] = 'You must be logged in to perform that action'
    redirect_to root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[edit update show destroy]
  before_action :require_user, except: %i[index show]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5).order('created_at DESC')
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      flash[:success] = 'Article created successfully'
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article updated successfully'
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show; end

  def destroy
    @article.destroy
    flash[:danger] = 'Article deleted successfully'
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    return unless current_user != @article.user and !current_user.admin?

    flash[:danger] = 'You cannot perform this action'
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: %i[index show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = 'Category was successfully created'
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      flash[:success] = 'Category name updated successfully'
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    return unless !logged_in? || (logged_in? && !current_user.admin?)

    flash[:danger] = 'Only admins can perform that action'
    redirect_to categories_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'You have successfully logged in'
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy]
  before_action :require_admin, only: %i[destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "It's nice to have you here #{@user.username}!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = 'Details updated successfully'
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user.destroy
    flash[:danger] = 'User and all articles created by user have been deleted'
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    return unless current_user != @user and !current_user.admin?

    flash[:danger] = 'You can only edit your own profile'
    redirect_to root_path
  end

  def require_admin
    return unless logged_in? and !current_user.admin?

    flash[:danger] = 'Only admin users can perform that action'
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: 'rounded-circle mb-3')
  end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
  <div class="row mx-1 mb-4">
    <div class="bg-secondary col-md-8 offset-md-2 p-4 rounded" style="--bs-bg-opacity: .1;">
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
      </div>

      <div class="py-3">
        <%= truncate(article.description, length: 100) %>
        <div class="mt-4">
          <small class="text-muted">
            Created by: <%= article.user.username %>, 
            <%= time_ago_in_words(article.created_at) %> ago
          </small>
        </div>
      </div>

      <% if article.categories.any? %>
        <p>Categories: <%= render article.categories %></p>
      <% end %>

      <% if logged_in? && (current_user == article.user || current_user.admin?) %>
        <div class="article-actions">
          <%= link_to 'Edit article', edit_article_path(article), class: "btn btn-sm btn-info" %>
          <%= link_to 'Delete article', article_path(article), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-danger" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_with model: @article, data: {turbo: false} do |f| %>
  <div class="row mb-3">
    <div class="col-sm-2 col-form-label">
      <%= f.label :title %>
    </div>    
    <div class="col-sm-8">
      <%= f.text_field :title, class: "form-control", placeholder: "Title of article" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-2 col-form-label">
      <%= f.label :description %>
    </div>    
    <div class="col-sm-8">
      <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description goes here" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="offset-md-2 col-sm-10">
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |opt| %>
        <div class="form-check form-check-inline">
          <%= opt.check_box class: "form-check-input" %>
          <%= opt.label class: "form-check-label" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="offset-md-2 col-sm-10">
      <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>

<div class="row mb-3">
  <div class="offset-md-2 col-sm-10">
    <%= link_to 'Cancel request and return to articles listing', articles_path %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="mb-4 text-center">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mb-3">All articles</h1>

<%= render 'article', obj: @articles %>

<div class="mt-5 d-flex justify-content-center">
  <%= will_paginate(@articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

app/views/articles/new.html.erb
<h1 class="mb-4 text-center">Create an article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mb-3"><%= @article.title %></h2>

<div class="row mx-1">
  <div class="bg-secondary col-md-8 offset-md-2 p-4 rounded" style="--bs-bg-opacity: .1;">
    <h4 class="text-center">Description</h4>

    <hr>

    <%= simple_format(@article.description) %>

    <% if @article.categories.any? %>
      <p>Categories: <%= render @article.categories %></p>
    <% end %>

    <div class="mt-4">
      <small class="text-muted">
        Written by: <%= @article.user.username %>
      </small>
    </div>

    <div class="article-actions">
      <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to 'Edit article', edit_article_path(@article), class: "btn btn-sm btn-primary" %>
        <%= link_to 'Delete article', article_path(@article), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-danger" %>
      <% end %>
      <%= link_to 'View all articles', articles_path, class: "btn btn-sm btn-success" %>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_with model: @category, data: {turbo: false} do |f| %>
  <div class="row mb-3">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>    
    <div class="col-sm-8">
      <%= f.text_field :name, class: "form-control", placeholder: "Category name" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="offset-md-2 col-sm-10">
    <%= f.submit class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>

<div class="row mb-3">
  <div class="offset-md-2 col-sm-10">
    <%= link_to 'Cancel request and return to categories listing', categories_path %>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mb-3">Edit category name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mb-3">All categories</h1>

<% @categories.each do |category| %>
  <div class="row mx-1 mb-4">
    <div class="bg-secondary col-md-8 offset-md-2 p-4 rounded" style="--bs-bg-opacity: .1;">
      <div class="article-title category-title text-center">
        <div>
          <%= link_to category.name, category_path(category) %>
          <li class="badge bg-info"><%= category.articles.count %></li>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="mt-5 d-flex justify-content-center">
  <%= will_paginate(@categories, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mb-3">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mb-1"><%= "Category: " + @category.name %></h1>

<div class="text-center mb-3">
  <% if logged_in? and current_user.admin? %>
    <span class="badge">
      <%= link_to 'Edit category name', edit_category_path(@category) %>
    </span>
  <% end %>
</div>

<%= render 'articles/article', obj: @category_articles %>

<% if @category_articles.empty? %>
  <div class="alert alert-info text-center">
    No articles found in this category
  </div>
<% end %>

<div class="mt-5 d-flex justify-content-center">
  <%= will_paginate(@category_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <p>&copy; dewslyse</p>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row mt-3">
  <div class="offset-md-2 col-md-8">
    <% flash.each do |name, msg| %>
      <div class='alert alert-dismissible alert-<%="#{name}" %>'>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to '💭 Musings', root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Articles', articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'New Article', new_article_path, class: "dropdown-item" %></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
        <% end %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'All Categories', categories_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <% Category.all.each do |category| %>
                <li><%= link_to category.name, category_path(category), class: "dropdown-item" %></li>
              <% end %>
              
              <% if logged_in? && current_user.admin? %>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to 'Create New Category', new_category_path, class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </li>
      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

      <ul class="navbar-nav mx-5">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              My Profile <%= "(Admin)" if current_user.admin? %>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit Profile', edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to 'View Profile', user_path(current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>

          <li class="nav-item">
            <%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %>
          </li>          
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Signup', signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musings Blog App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Musings Blog App</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="homepage">
  <div class="caption-box">
    <h1>Musings</h1>
    <p>Share your thoughts with the world</p>
  </div>
  <%= link_to 'Sign up now', signup_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row mb-3">
    <div class="offset-md-2 col-md-8">
      <div class="alert alert-danger">
        <h4><%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:</h4>
        <ul>
          <% obj.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with model: @user, data: {turbo: false} do |f| %>
  <div class="row mb-3">
    <div class="col-sm-2 col-form-label">
      <%= f.label :username %>
    </div>    
    <div class="col-sm-8">
      <%= f.text_field :username, class: "form-control", placeholder: "Enter username" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>    
    <div class="col-sm-8">
      <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>    
    <div class="col-sm-8">
      <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
    </div>
  </div>

  <div class="row mb-3">
    <div class="offset-md-2 col-sm-10">
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update details", class: "btn btn-primary btn-lg") %>
    </div>
  </div>
<% end %>

<div class="row mb-3">
  <div class="offset-md-2 col-sm-10">
    <%= link_to 'Cancel request and return to articles listing', articles_path %>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mb-3">Edit Details</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mb-3">All users</h1>

<% @users.each do |user| %>
  <div class="row mx-1 mb-4">
    <div class="bg-secondary col-md-8 offset-md-2 p-4 rounded" style="--bs-bg-opacity: .1;">
      <div class="article-title d-flex justify-content-between align-items-center">
        <div>
          <%= link_to gravatar_for(user), user_path(user) %>
        </div>
        <div>
          <%= link_to user.username, user_path(user) %>
        </div>
      </div>

      <div class="py-3">
        <div class="mt-4 d-flex justify-content-between">
          <small class="text-muted">
            <%= pluralize(user.articles.count, "article") if user.articles %> 
          </small>

          <% if logged_in? && current_user.admin? %>
            <%= link_to 'Delete user', user_path(user), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-sm btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="mt-5 d-flex justify-content-center">
  <%= will_paginate(@users, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mb-3">Sign Up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mb-3">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
  <div class="col-md-4 offset-md-4 text-center">
    <%= gravatar_for(@user) %>
  </div>
</div>

<h3 class="text-center mb-4"><%= @user.username %>'s articles</h3>

<% if @user.articles.any? %>
  <%= render 'articles/article', obj: @user_articles %>
<% else %>
  <p class="text-center">This user has not written any articles yet</p>
<% end %>

<div class="mt-5 d-flex justify-content-center">
  <%= will_paginate(@user_articles, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer) %>
</div>